// userReducer
export const SET_USER = "SET_USER";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const UPDATE_USER = "UPDATE_USER";
export const RESET_USER = "RESET_USER";

// customersReducer
export const SET_CUSTOMER = "SET_CUSTOMER";
export const SET_CUSTOMERS = "SET_CUSTOMERS";
export const SET_CUSTOMERS_PAGINATION = "SET_CUSTOMERS_PAGINATION";
export const RESET_CUSTOMERS = "RESET_CUSTOMERS";

// commonReducer
export const SET_SHOW_LODER = "SET_SHOW_LODER";
export const SET_ERRORS = "SET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";
export const SET_MESSAGE = "SET_MESSAGE";

// usersReducer
export const SET_VIEW_USER = "SET_VIEW_USER";
export const SET_USERS = "SET_USERS";
export const SET_TOTAL_USERS = "SET_TOTAL_USERS";
export const SET_USERS_PAGINATION = "SET_USERS_PAGINATION";
export const RESET_USERS = "RESET_USERS";

// helpfulTipsReducer
export const SET_HELPFUL_TIP = "SET_HELPFUL_TIP";
export const SET_HELPFUL_TIPS = "SET_HELPFUL_TIPS";
export const SET_HELPFUL_TIPS_PAGINATION = "SET_HELPFUL_TIPS_PAGINATION";
export const RESET_HELPFUL_TIPS = "RESET_HELPFUL_TIPS";

// homeCategoriesReducer
export const SET_HOME_CATEGORIE = "SET_HOME_CATEGORIE";
export const SET_HOME_CATEGORIES = "SET_HOME_CATEGORIES";
export const SET_HOME_CATEGORIES_PAGINATION = "SET_HOME_CATEGORIES_PAGINATION";
export const RESET_HOME_CATEGORIES = "RESET_HOME_CATEGORIES";

// applicationSettingsReducer
export const SET_APPLICATION_SETTING = "SET_APPLICATION_SETTING";
export const SET_APPLICATION_SETTINGS = "SET_APPLICATION_SETTINGS";
export const SET_APPLICATION_SETTINGS_PAGINATION = "SET_APPLICATION_SETTINGS_PAGINATION";
export const RESET_APPLICATION_SETTINGS = "RESET_APPLICATION_SETTINGS";

// promotionBannersReducer
export const SET_PROMOTION_BANNER = "SET_PROMOTION_BANNER";
export const SET_PROMOTION_BANNERS = "SET_PROMOTION_BANNERS";
export const SET_PROMOTION_BANNERS_PAGINATION = "SET_PROMOTION_BANNERS_PAGINATION";
export const RESET_PROMOTION_BANNERS = "RESET_PROMOTION_BANNERS";

// questionsReducer
export const SET_QUESTION = "SET_QUESTION";
export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_QUESTIONS_PAGINATION = "SET_QUESTIONS_PAGINATION";
export const RESET_QUESTIONS = "RESET_QUESTIONS";

// entityAndAttributesReducer
export const SET_ENTITIES = "SET_ENTITIES";
export const SET_ATTRIBUTES = "SET_ATTRIBUTES";
export const RESET_ENTITY_AND_ATTRIBUTES = "RESET_ENTITY_AND_ATTRIBUTES";

// plansReducer
export const SET_PLAN = "SET_PLAN";
export const SET_PLANS = "SET_PLANS";
export const SET_PLANS_PAGINATION = "SET_PLANS_PAGINATION";
export const RESET_PLANS = "RESET_PLANS";

// mealsReducer
export const SET_MEAL = "SET_MEAL";
export const SET_MEALS = "SET_MEALS";
export const SET_MEALS_PAGINATION = "SET_MEALS_PAGINATION";
export const RESET_MEALS = "RESET_MEALS";

// foodTypesReducer
export const SET_FOOD_TYPE = "SET_FOOD_TYPE";
export const SET_FOOD_TYPES = "SET_FOOD_TYPES";
export const SET_FOOD_TYPES_PAGINATION = "SET_FOOD_TYPES_PAGINATION";
export const RESET_FOOD_TYPES = "RESET_FOOD_TYPES";

// calorieCalculationsReducer
export const SET_CALORIE_BY_TITLE = "SET_CALORIE_BY_TITLE";
export const SET_CALORIE_CALCULATION = "SET_CALORIE_CALCULATION";
export const SET_CALORIE_CALCULATIONS = "SET_CALORIE_CALCULATIONS";
export const SET_CALORIE_CALCULATIONS_PAGINATION = "SET_CALORIE_CALCULATIONS_PAGINATION";
export const RESET_CALORIE_CALCULATIONS = "RESET_CALORIE_CALCULATIONS";

// workoutsReducer
export const SET_WORKOUT = "SET_WORKOUT";
export const SET_WORKOUTS = "SET_WORKOUTS";
export const SET_WORKOUTS_PAGINATION = "SET_WORKOUTS_PAGINATION";
export const RESET_WORKOUTS = "RESET_WORKOUTS";

// medicalInstructionsReducer
export const SET_MEDICAL_INSTRUCTION = "SET_MEDICAL_INSTRUCTION";
export const SET_MEDICAL_INSTRUCTIONS = "SET_MEDICAL_INSTRUCTIONS";
export const SET_MEDICAL_INSTRUCTIONS_PAGINATION = "SET_MEDICAL_INSTRUCTIONS_PAGINATION";
export const RESET_MEDICAL_INSTRUCTIONS = "RESET_MEDICAL_INSTRUCTIONS";

// contentOfTheDaysReducer
export const SET_CONTENT_OF_THE_DAY = "SET_CONTENT_OF_THE_DAY";
export const SET_CONTENT_OF_THE_DAYS = "SET_CONTENT_OF_THE_DAYS";
export const SET_CONTENT_OF_THE_DAYS_PAGINATION = "SET_CONTENT_OF_THE_DAYS_PAGINATION";
export const RESET_CONTENT_OF_THE_DAYS = "RESET_CONTENT_OF_THE_DAYS";

// dailyTasksReducer
export const SET_DAILY_TASK = "SET_DAILY_TASK";
export const SET_DAILY_TASKS = "SET_DAILY_TASKS";
export const SET_DAILY_TASKS_PAGINATION = "SET_DAILY_TASKS_PAGINATION";
export const RESET_DAILY_TASKS = "RESET_DAILY_TASKS";
